// LamQuant OpEvent types — TS view of specs/op-events.schema.json.
//
// Hand-written rather than autogenerated from the JSON Schema because the
// schema is small (six variants, ≤8 fields total) and pulling in
// json-schema-to-typescript as an npm prebuild step adds CI friction
// without a meaningful win at this size. The schema parity test in
// tests/schema_parity.rs in this compatibility crate still pins the wire format,
// and we exercise this TS file via a tiny round-trip check
// (gui/scripts/check-op-events.mjs) that the Rust test invokes.

export type OpEventType =
  | 'Started'
  | 'Progress'
  | 'FileDone'
  | 'Done'
  | 'Error'
  | 'Log';

interface OpEventBase {
  type: OpEventType;
  /** Wall-clock milliseconds since UNIX epoch at the point of emission. */
  ts_ms: number;
}

export interface OpEventStarted extends OpEventBase {
  type: 'Started';
  /** Canonical op id from specs/ui-parity.md::Op IDs. */
  op_id: string;
  /** Best-effort total work units. Null if unknown. */
  total?: number | null;
}

export interface OpEventProgress extends OpEventBase {
  type: 'Progress';
  current: number;
  total: number;
  message: string;
}

export interface OpEventFileDone extends OpEventBase {
  type: 'FileDone';
  path: string;
  success: boolean;
  ms: number;
  /** Compression ratio (output_bytes / input_bytes). Null when not applicable. */
  cr?: number | null;
  bytes_in?: number | null;
  bytes_out?: number | null;
  samples?: number | null;
  duration_s?: number | null;
  n_channels?: number | null;
  sample_rate?: number | null;
  sha256?: string | null;
  n_windows?: number | null;
}

export interface OpEventDone extends OpEventBase {
  type: 'Done';
  message: string;
}

export interface OpEventError extends OpEventBase {
  type: 'Error';
  /** Cancellations contain the substring "cancelled" — distinguish on that. */
  message: string;
}

export interface OpEventLog extends OpEventBase {
  type: 'Log';
  message: string;
}

export type OpEvent =
  | OpEventStarted
  | OpEventProgress
  | OpEventFileDone
  | OpEventDone
  | OpEventError
  | OpEventLog;

/**
 * Coarse-grained op state for poll-based readers (Tauri GUI).
 * Mirrors `lamquant_ops::sink::OpState` so the snapshot returned from
 * the `op_snapshot` Tauri command deserializes cleanly.
 */
export type OpState =
  | 'Pending'
  | 'Running'
  | 'Cancelling'
  | 'Done'
  | 'Failed';

/**
 * Snapshot returned by the `op_snapshot` Tauri command. The frontend polls
 * this every 200ms while an op is running — Tauri's event delivery is less
 * reliable than its sync command path under load (window minimize, HMR,
 * 100-event/sec stress), so polling is the source of truth for incremental
 * progress while events fire only on state transitions.
 */
export interface OpProgressSnapshot {
  op_id: string;
  state: OpState;
  current: number;
  total: number;
  message: string;
  last_file?: string | null;
  terminal_message?: string | null;
  /** Wall-clock ms of the latest update. Detect stalled runs by diffing now-vs-this. */
  updated_ms: number;
}

/** Heuristic: is the message a user-cancelled abort rather than a real failure? */
export function isCancelledMessage(message: string): boolean {
  return message.includes('cancelled');
}
