"""
Op-event emitter — Python side of the LamQuant op contract.

Wire format is the canonical JSON Schema at ``specs/op-events.schema.json``.
Rust, Python, and TS all consume the same shape; drift is caught by
``crates/lamquant-ops/tests/schema_parity.rs``.

Python is **both** a producer and a consumer of OpEvents:

  - Producer: when the Python TUI runs an op natively (training launches,
    ML pipeline jobs, the legacy Python codec backend), it calls these
    functions to emit JSON lines on stdout that the parent process (Rust
    TUI or Tauri GUI) parses identically to ``lml --emit-json-events``.

  - Consumer: when the Python TUI shells out to ``lml`` it parses the
    same JSON-line stream the other UIs see. ``parse_line`` is the entry
    point for that path.

The module is hand-rolled rather than autogenerated to keep the runtime
dependency count at zero — the schema is small enough (six event types,
≤8 fields total) that a generated dataclass is overkill. The
``schema_parity`` test exercises Rust ↔ Python round-trip by spawning
``python -m lamquant_codec.cli.op_emit --check`` against the canonical
fixture, so any drift fails the build.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from dataclasses import dataclass, field
from typing import Any, Iterable, Optional


# ── Wire-format constants ─────────────────────────────────────────────────
# Variant names match the canonical JSON Schema's "type" enum exactly.
EVENT_STARTED = "Started"
EVENT_PROGRESS = "Progress"
EVENT_FILE_DONE = "FileDone"
EVENT_DONE = "Done"
EVENT_ERROR = "Error"
EVENT_LOG = "Log"

VALID_EVENT_TYPES = frozenset({
    EVENT_STARTED, EVENT_PROGRESS, EVENT_FILE_DONE,
    EVENT_DONE, EVENT_ERROR, EVENT_LOG,
})


def _now_ms() -> int:
    """Wall-clock milliseconds since UNIX epoch — matches Rust ``OpEvent::now_ms``."""
    return int(time.time() * 1000)


# ── Producer API ──────────────────────────────────────────────────────────

def _emit(payload: dict) -> None:
    """Write a single OpEvent JSON line to stdout and flush.

    Flushing on every event is intentional: the parent process polls or
    streams stdout line-by-line, so buffering would make progress reporting
    appear stalled. The cost is negligible (events arrive at ≤100 Hz under
    load).
    """
    sys.stdout.write(json.dumps(payload, separators=(",", ":")))
    sys.stdout.write("\n")
    sys.stdout.flush()


def started(op_id: str, total: Optional[int] = None) -> None:
    """Emit a ``Started`` event. Required at the start of every op."""
    payload = {"type": EVENT_STARTED, "ts_ms": _now_ms(), "op_id": op_id}
    if total is not None:
        payload["total"] = int(total)
    _emit(payload)


def progress(current: int, total: int, message: str) -> None:
    """Emit a ``Progress`` event. SHOULD fire at most ~10 Hz to avoid spam."""
    _emit({
        "type": EVENT_PROGRESS, "ts_ms": _now_ms(),
        "current": int(current), "total": int(total),
        "message": str(message),
    })


def file_done(
    path: str,
    success: bool,
    ms: int,
    cr: Optional[float] = None,
    bytes_in: Optional[int] = None,
    bytes_out: Optional[int] = None,
    samples: Optional[int] = None,
    duration_s: Optional[float] = None,
    n_channels: Optional[int] = None,
    sample_rate: Optional[float] = None,
    sha256: Optional[str] = None,
    n_windows: Optional[int] = None,
) -> None:
    """Emit a ``FileDone`` event for one file in a multi-file op.

    Optional telemetry fields (bytes_in/out, samples, duration_s,
    n_channels, sample_rate, sha256, n_windows) drive the Rust TUI's
    live compress dashboard. Pass None when a field isn't known.
    Schema mirror: ``specs/op-events.schema.json``.
    """
    payload = {
        "type": EVENT_FILE_DONE, "ts_ms": _now_ms(),
        "path": str(path), "success": bool(success), "ms": int(ms),
    }
    if cr is not None:
        payload["cr"] = float(cr)
    if bytes_in is not None:
        payload["bytes_in"] = int(bytes_in)
    if bytes_out is not None:
        payload["bytes_out"] = int(bytes_out)
    if samples is not None:
        payload["samples"] = int(samples)
    if duration_s is not None:
        payload["duration_s"] = float(duration_s)
    if n_channels is not None:
        payload["n_channels"] = int(n_channels)
    if sample_rate is not None:
        payload["sample_rate"] = float(sample_rate)
    if sha256 is not None:
        payload["sha256"] = str(sha256)
    if n_windows is not None:
        payload["n_windows"] = int(n_windows)
    _emit(payload)


def done(message: str) -> None:
    """Emit a terminal ``Done`` event. The op ended successfully."""
    _emit({"type": EVENT_DONE, "ts_ms": _now_ms(), "message": str(message)})


def error(message: str) -> None:
    """Emit a terminal ``Error`` event. The op failed OR was cancelled.

    Cancellation events MUST contain the substring ``"cancelled"`` so
    consumers can distinguish user-initiated abort from a real failure
    without inventing a new variant.
    """
    _emit({"type": EVENT_ERROR, "ts_ms": _now_ms(), "message": str(message)})


def log(message: str) -> None:
    """Emit a free-form ``Log`` line — for stdout/stderr passthrough."""
    _emit({"type": EVENT_LOG, "ts_ms": _now_ms(), "message": str(message)})


# ── Consumer API ──────────────────────────────────────────────────────────

@dataclass
class OpEvent:
    """Parsed view of one OpEvent JSON line.

    Fields are populated only for variants that carry them; the discriminator
    lives in ``type``. This is a thin DTO — consumers SHOULD switch on
    ``type`` and read the variant-specific fields directly.
    """
    type: str
    ts_ms: int
    op_id: Optional[str] = None
    total: Optional[int] = None
    current: Optional[int] = None
    message: Optional[str] = None
    path: Optional[str] = None
    success: Optional[bool] = None
    cr: Optional[float] = None
    ms: Optional[int] = None
    raw: dict = field(default_factory=dict)


def parse_line(line: str) -> OpEvent:
    """Parse a single JSON line into an :class:`OpEvent`.

    Raises ``ValueError`` on malformed JSON or unknown ``type`` value. The
    Python TUI's subprocess reader uses this on every line it gets back from
    ``lml --emit-json-events``.
    """
    try:
        data = json.loads(line)
    except json.JSONDecodeError as e:
        raise ValueError(f"OpEvent JSON parse: {e}") from e
    if not isinstance(data, dict):
        raise ValueError(f"OpEvent must be a JSON object, got {type(data).__name__}")
    t = data.get("type")
    if t not in VALID_EVENT_TYPES:
        raise ValueError(f"unknown OpEvent type: {t!r}")
    ts = data.get("ts_ms")
    if not isinstance(ts, int):
        raise ValueError("OpEvent.ts_ms must be an integer")
    return OpEvent(
        type=t,
        ts_ms=ts,
        op_id=data.get("op_id"),
        total=data.get("total"),
        current=data.get("current"),
        message=data.get("message"),
        path=data.get("path"),
        success=data.get("success"),
        cr=data.get("cr"),
        ms=data.get("ms"),
        raw=data,
    )


def parse_lines(stream: Iterable[str]) -> Iterable[OpEvent]:
    """Iterate ``OpEvent``s from a line-oriented stream (e.g. subprocess stdout).

    Lines that fail to parse are skipped with a warning printed to stderr —
    a single malformed line should not abort consumption of the rest of the
    stream. Callers that need stricter behaviour can use :func:`parse_line`
    directly in a ``for line in stream`` loop.
    """
    for line in stream:
        line = line.rstrip("\n")
        if not line:
            continue
        try:
            yield parse_line(line)
        except ValueError as e:
            sys.stderr.write(f"op_emit: dropping malformed event line: {e}\n")


# ── CLI / self-test (--check) ─────────────────────────────────────────────

def _check_round_trip() -> int:
    """Self-test entry point used by ``crates/lamquant-ops/tests/schema_parity.rs``.

    Reads the canonical fixture, asserts every line round-trips through
    :func:`parse_line` cleanly, then re-emits identical JSON lines so a
    Rust-side diff can confirm the wire format is byte-stable across
    languages. Returns 0 on success, 1 on any drift.
    """
    from lamquant_codec._paths import REPO_ROOT as here
    fixture = here / "crates" / "lamquant-ops" / "tests" / "fixtures" / "op-events-sample.jsonl"
    if not fixture.exists():
        print(f"fixture not found: {fixture}", file=sys.stderr)
        return 1

    failures = 0
    for i, raw in enumerate(fixture.read_text().splitlines(), start=1):
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        try:
            ev = parse_line(raw)
        except ValueError as e:
            print(f"line {i}: parse failed: {e}", file=sys.stderr)
            failures += 1
            continue
        if ev.type not in VALID_EVENT_TYPES:
            print(f"line {i}: bad type {ev.type!r}", file=sys.stderr)
            failures += 1
        # Field presence sanity per variant.
        required = {
            EVENT_STARTED: ("op_id",),
            EVENT_PROGRESS: ("current", "total", "message"),
            EVENT_FILE_DONE: ("path", "success", "ms"),
            EVENT_DONE: ("message",),
            EVENT_ERROR: ("message",),
            EVENT_LOG: ("message",),
        }[ev.type]
        for name in required:
            if getattr(ev, name) is None:
                print(f"line {i}: variant {ev.type} missing {name}", file=sys.stderr)
                failures += 1
    if failures:
        print(f"op_emit --check: {failures} failure(s)", file=sys.stderr)
        return 1
    print("op_emit --check: OK")
    return 0


def _main() -> int:
    parser = argparse.ArgumentParser(prog="python -m lamquant_codec.cli.op_emit")
    parser.add_argument("--check", action="store_true",
                        help="Round-trip the canonical fixture and exit.")
    args = parser.parse_args()
    if args.check:
        return _check_round_trip()
    parser.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
